baseURL = 'https://flamurrogova.github.io/'
languageCode = 'en-us'
title = "Random Ramblings on Tech"
theme = 'paper'


sectionPagesMenu = 'main'


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'flamurrogova'                 # github.com/YOUR_GITHUB_ID

